name = "gut-feel-exchange"
pages_build_output_dir = "./out"
compatibility_date = "2025-09-01"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]


[[kv_namespaces]]
# Replace these placeholder IDs after running `npx wrangler kv namespace create PREDICTIONS_KV`
binding = "PREDICTIONS_KV"
id = "623e28e5b2df4115acb606f4b91efafb"
preview_id = "02d525b6219740efa148c43cd859c755"
